name: GitHub Actions PyTest
run-name: ${{ github.actor }} is testing out Unit Tests 🚀
on: [push]
permissions: read-all

jobs:
  build:
    runs-on: ubuntu-22.04
    environment: env
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Set Environment Variables
        run: |
          echo "export API_URL_BASE_TEST=${{ secrets.API_URL_BASE_TEST }}" >> $GITHUB_ENV
      - name: Print Environment Variables
        run: |
          echo $API_URL_BASE_TEST
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest
      - name: Run pytest
        run: |
          pytest
